/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IPSET_TEST_RPC_H_RPCGEN
#define _IPSET_TEST_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ip4_addr {
	uint32_t addr;
};
typedef struct ip4_addr ip4_addr;

struct ip6_addr {
	u_char addr[16];
};
typedef struct ip6_addr ip6_addr;

struct test_ipaddr_in_ipset_req {
	char setname[32];
	int af;
	ip4_addr ip4addr;
	ip6_addr ip6addr;
};
typedef struct test_ipaddr_in_ipset_req test_ipaddr_in_ipset_req;

#define IPSET_TEST_PROG 0x200000f1
#define IPSET_TEST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TEST_IPADDR_IN_IPSET 1
extern  int * test_ipaddr_in_ipset_1(test_ipaddr_in_ipset_req *, CLIENT *);
extern  int * test_ipaddr_in_ipset_1_svc(test_ipaddr_in_ipset_req *, struct svc_req *);
extern int ipset_test_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TEST_IPADDR_IN_IPSET 1
extern  int * test_ipaddr_in_ipset_1();
extern  int * test_ipaddr_in_ipset_1_svc();
extern int ipset_test_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ip4_addr (XDR *, ip4_addr*);
extern  bool_t xdr_ip6_addr (XDR *, ip6_addr*);
extern  bool_t xdr_test_ipaddr_in_ipset_req (XDR *, test_ipaddr_in_ipset_req*);

#else /* K&R C */
extern bool_t xdr_ip4_addr ();
extern bool_t xdr_ip6_addr ();
extern bool_t xdr_test_ipaddr_in_ipset_req ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IPSET_TEST_RPC_H_RPCGEN */
