/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ipset_test_rpc.h"

bool_t
xdr_ip4_addr (XDR *xdrs, ip4_addr *objp)
{
	// register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, &objp->addr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ip6_addr (XDR *xdrs, ip6_addr *objp)
{
	// register int32_t *buf;

	// int i;
	 if (!xdr_vector (xdrs, (char *)objp->addr, 16,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_test_ipaddr_in_ipset_req (XDR *xdrs, test_ipaddr_in_ipset_req *objp)
{
	// register int32_t *buf;

	// int i;
	 if (!xdr_vector (xdrs, (char *)objp->setname, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->af))
		 return FALSE;
	 if (!xdr_ip4_addr (xdrs, &objp->ip4addr))
		 return FALSE;
	 if (!xdr_ip6_addr (xdrs, &objp->ip6addr))
		 return FALSE;
	return TRUE;
}
